apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.registry.regconfig }}
  namespace: {{ .Values.namespace }}
data:
  EUREKA_SERVER_ADDRESS: http://eureka-0.eureka:8761/eureka,http://eureka-1.eureka:8761/eureka,http://eureka-2.eureka:8761/eureka
  ENVIRONMENT: prod
