apiVersion: v1
kind: PersistentVolume
metadata:
  name: sts-pv0
  labels:
    type: local
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  capacity:
    {{- include "hperegistrypv.capacity" . | nindent 4 }}
  accessModes:
    - ReadWriteMany
  nfs:
    {{- include "hperegistrypv.server" . | nindent 4 }}
    path: "/srv/nfs/sts/sts0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sfs-pv1
  labels:
    type: local
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  capacity:
    {{- include "hperegistrypv.capacity" . | nindent 4 }}
  accessModes:
    - ReadWriteMany
  nfs:
    {{- include "hperegistrypv.server" . | nindent 4 }}
    path: "/srv/nfs/sts/sts1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sfs-pv2
  labels:
    type: local
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: manual
  capacity:
    {{- include "hperegistrypv.capacity" . | nindent 4 }}
  accessModes:
    - ReadWriteMany
  nfs:
    {{- include "hperegistrypv.server" . | nindent 4 }}    
    path: "/srv/nfs/sts/sts2"

